[workspace]
members = [
  "./backends/llmrs",
  "./backends/llmrs-cli",
  "./backends/outsource",
  "./backends/outsource-cli",
  "./core",
  "./core-cli",
  "./frontends/chat",
  "./frontends/codeassist",
  "./util"
]
