[package]
name = "llmvm-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
hyper = { version = "0.14", optional = true, features = ["http1"] }
thiserror = "1.0"
tower = { version = "0.4", optional = true, features = ["timeout"] }
tokio = { version = "1.27", optional = true, features = ["io-std", "io-util", "process", "rt", "sync"] }
tracing = "0.1"

[features]
tower = ["dep:tower"]
jsonrpc = []
stdio = ["tower", "dep:tokio", "jsonrpc"]
http-client = ["tower", "dep:hyper", "hyper?/client"]
http-server = ["tower", "dep:hyper", "hyper?/server"]

