[package]
name = "llmvm-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
futures = "0.3"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sweetlinks = { version = "0.1", path = "../../sweetlinks" }
tokio = { version = "1.27", optional = true, features = ["rt"] }

[features]
http-client = ["sweetlinks/http-client"]
http-server = ["sweetlinks/http-server"]
stdio-client = ["sweetlinks/stdio-client"]
stdio-server = ["sweetlinks/stdio-server"]