[package]
name = "llmvm-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
futures = "0.3"
llmvm-util = { version = "0.1", path = "../util" }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
multilink = { version = "0.1", path = "../../multilink" }
tokio = { version = "1.27", optional = true, features = ["rt"] }

[features]
http-client = ["multilink/http-client"]
http-server = ["multilink/http-server"]
stdio-client = ["multilink/stdio-client"]
stdio-server = ["multilink/stdio-server"]