[package]
name = "llmvm-protocol"
version = "0.1.0"
edition = "2021"

[dependencies]
async-trait = "0.1"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
axum = { version = "0.6", optional = true }
thiserror = "1.0"
tower = { version = "0.4", optional = true, features = ["timeout"] }
tokio = { version = "1.27", optional = true, features = ["io-std", "io-util", "process"] }

[features]
http_server = ["dep:axum"]
stdio = ["dep:tower", "dep:tokio"]

