[package]
name = "llmvm-outsource"
version = "0.1.0"
edition = "2021"

[dependencies]
async-stream = "0.3"
futures = "0.3"
llmvm-protocol = { path = "../../protocol" }
reqwest = { version = "0.11", features = ["json", "stream"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
thiserror = "1.0"
strum = "0.24"
strum_macros = "0.24"
