[package]
name = "llmvm-outsource"
version = "0.1.0"
edition = "2021"

[dependencies]
llmvm-protocol = { path = "../../protocol", features = ["stdio"] }
reqwest = { version = "0.11", features = ["json"] }
serde = "1.0"
serde_json = "1.0"
thiserror = "1.0"
strum = "0.24"
strum_macros = "0.24"
