[package]
name = "llmvm-backend-util"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.1", features = ["derive"] }
llmvm-protocol = { path = "../../protocol" }
serde_json = "1.0"